### ISSUE TITLE
faq: will the automatization used this year again?

### ISSUE THREAD

**Issue by DevVersion** [Werdenfels-Gymnasium/AutoAnnual#1]
Will the automatization used this year as well?

**Comment by IngolfSchmitt** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

Yes - of course!
It is agreat automatism.
If I remember the right way, there was only one "Space" too much
within the teachers-text created. Can you please change it?

Am 25.04.2016 um 21:48 schrieb Paul Gschwendtner:
> Assigned #1 
> <https://github.com/Werdenfels-Gymnasium/AutoAnnual/issues/1> to 
> @IngolfSchmitt <https://github.com/IngolfSchmitt>.
> 
> — You are receiving this because you were mentioned. Reply to this
> email directly or view it on GitHub 
> <https://github.com/Werdenfels-Gymnasium/AutoAnnual/issues/1#event-640532436>
>
> 
- -- 
Ingolf Schmitt
Schwarzenkopfweg 14
82491 Grainau
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2.0.22 (GNU/Linux)

iEYEARECAAYFAlcedlgACgkQl9VDzohFjDKKvQCcDHcZooBDlmfoyFr5FDEzvmT/
h4cAn2yv4De6CRUp6MJKCL/KPXkTYTEL
=5zdr
-----END PGP SIGNATURE-----
